title: Yongsheng Yu
position: Assistant Engineer
affiliation: Institute of Software Chinese Academy of Sciences
email: yuyongsheng19@mails.ucas.ac.cn
keywords: yongsheng yu, yeates, yeates yu, yu yongsheng, yuyongsheng, yongshengyu
google_scholar: https://scholar.google.com/citations?user=QXF5p7QAAAAJ
github_link: https://github.com/yeates
linkedin: https://www.linkedin.cn/incareer/in/yongsheng-yu-87b7b2150
avatar: ./assets/img/avatar.jpg
google_analytics: UA-172331442-1
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Yongsheng Yu's academic homepage.
canonical: https://www.yongshengyu.com
twitter: https://twitter.com/YeatesYu

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - run-jekyll.sh
  - minimal-light.gemspec
  - CNAME
