title: Yongsheng Yu
position: Ph.D. Student
affiliation: University of Rochester
email: yyu90 at ur.rochester.edu
keywords: yongsheng yu, yeates, yeates yu, yu yongsheng, yuyongsheng, yongshengyu
google_scholar: https://scholar.google.com/citations?user=QXF5p7QAAAAJ
github_link: https://github.com/yeates
linkedin: https://www.linkedin.com/in/yongsheng-yu-87b7b2150/
avatar: ./assets/img/avatar_1.jpg
google_analytics: UA-172331442-1
favicon: ./assets/img/favicon.jpg
favicon_dark: ./assets/img/favicon.jpg
description: Yongsheng's homepage
canonical: https://www.yongshengyu.com

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - run-jekyll.sh
  - minimal-light.gemspec
  - CNAME
