title: Yongsheng Yu
position: Assistant Engineer
affiliation: Institute of Software Chinese Academy of Sciences
email: yuyongsheng19@mails.ucas.ac.cn
keywords: yongsheng yu
google_scholar: 
github_link: https://github.com/yeates
linkedin: https://www.linkedin.cn/incareer/in/yongsheng-yu-87b7b2150
avatar: ./assets/img/avatar.png
google_analytics: UA-172331442-1
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Yongsheng Yu's academic homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
