title: Yongsheng Yu
position: Machine Learning Engineer
affiliation: ISCAS (Institute of Software, Chinese Academy of Sciences)
email: yuyongsheng19@mails.ucas.ac.cn
keywords: yongsheng yu
google_scholar: https://scholar.google.com/
github_link: https://github.com/yeates
linkedin: https://www.linkedin.com/
avatar: ./assets/img/avatar.png
google_analytics: 
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
